services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gtu_db
    volumes:
      - db_data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    ports:
      - "3000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gtu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
volumes:
  db_data: