services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gtu_db
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
     - app-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "3000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge